---
abstract: 'Sample perl extension module for your own.'
author:
  - 'Nobuo Danjou L<nobuo.danjou@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OreOre-Danjou-HelloWorld
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
